"""Create hoots and comments tables

Revision ID: 282618ce835e
Revises: 
Create Date: 2025-12-06 13:36:24.066047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '282618ce835e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoots_id'), 'hoots', ['id'], unique=False)
    op.drop_index(op.f('ix_teas_id'), table_name='teas')
    op.drop_table('teas')
    op.add_column('comments', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('hoot_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('comments_tea_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'hoots', ['hoot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'content')
    op.drop_column('comments', 'tea_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('tea_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_tea_id_fkey'), 'comments', 'teas', ['tea_id'], ['id'])
    op.drop_column('comments', 'hoot_id')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'text')
    op.create_table('teas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('teas_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teas_pkey')),
    sa.UniqueConstraint('name', name=op.f('teas_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_teas_id'), 'teas', ['id'], unique=False)
    op.drop_index(op.f('ix_hoots_id'), table_name='hoots')
    op.drop_table('hoots')
    # ### end Alembic commands ###
