"""Make company_name and title mandatory

Revision ID: 4cd58e0b2230
Revises: b089008269e5
Create Date: 2025-12-25 23:14:25.787741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd58e0b2230'
down_revision: Union[str, Sequence[str], None] = 'b089008269e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('invoices', sa.Column('title', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('title', sa.String(), nullable=True))

    # 2. Backfill existing data with default values
    op.execute("UPDATE invoices SET title = 'Invoice ' || invoice_number WHERE title IS NULL")
    op.execute("UPDATE quotes SET title = 'Quote #' || id WHERE title IS NULL")
    op.execute("UPDATE users SET company_name = 'Default Company' WHERE company_name IS NULL")

    # 3. Alter columns to set nullable=False
    op.alter_column('invoices', 'title', nullable=False)
    op.alter_column('quotes', 'title', nullable=False)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('quotes', 'title')
    op.drop_column('invoices', 'title')
    # ### end Alembic commands ###
